import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div
					style={{
						display: "flex",
						padding: "10px",
						gap: "10px",
					}}
				>
					<Link href="/">PT-BR</Link>
					<Link href="/en">EN</Link>
				</div>
				{children}
			</body>
		</html>
	);
}
